name: business
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  business_contract:
    path: ../business_contract

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
