name: presentation_contract
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.1
